// <auto-generated />
namespace EPTS.Repositories.WebServices.WebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EPTSContext19 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EPTSContext19));
        
        string IMigrationMetadata.Id
        {
            get { return "201709270216414_EPTSContext19"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
